name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository (Dockerfile repository)
    - name: Checkout Dockerfile repository
      uses: actions/checkout@v2

    # Step 2: Checkout the code repository
    - name: Checkout code repository
      uses: actions/checkout@v2
      with:
        repository: johnpapa/node-hello
        path: code-repo

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: docker build -t santhosh9790500644/bansira-node:latest -f Dockerfile code-repo

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push santhosh9790500644/bansira-node:latest
